"""added file and image field

Revision ID: 170977060734
Revises: c6ad13ee78aa
Create Date: 2022-02-04 19:28:14.277536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '170977060734'
down_revision = 'c6ad13ee78aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
