"""added hashed_password to user 

Revision ID: 1c14c1bfca9f
Revises: 449625aa3bb4
Create Date: 2022-01-16 23:29:45.874496

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c14c1bfca9f'
down_revision = '449625aa3bb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
