"""added file and image field

Revision ID: 2f7dd03db880
Revises: 5059b14dcdc6
Create Date: 2022-02-05 00:37:24.619006

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f7dd03db880'
down_revision = '5059b14dcdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('avatar', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['avatar'], ['imagefields.id'], name='fk_profiles_imagefields_id_avatar', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('users', sa.Column('profile', sa.Integer(), nullable=True))
    op.create_foreign_key('fk_users_profiles_id_profile', 'users', 'profiles', ['profile'], ['id'], ondelete='CASCADE')
    op.drop_column('users', 'full_name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('full_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_constraint('fk_users_profiles_id_profile', 'users', type_='foreignkey')
    op.drop_column('users', 'profile')
    op.drop_table('profiles')
    # ### end Alembic commands ###
