"""added file and image field

Revision ID: 35ae58237e59
Revises: ea9edc7e9cfa
Create Date: 2022-02-04 19:15:13.949170

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35ae58237e59'
down_revision = 'ea9edc7e9cfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
