"""added hashed_password to user 

Revision ID: 449625aa3bb4
Revises: 0a4faf0f43cb
Create Date: 2022-01-16 23:23:42.607334

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '449625aa3bb4'
down_revision = '0a4faf0f43cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hashed_password', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hashed_password')
    # ### end Alembic commands ###
