"""added file and image field

Revision ID: 4cde7b17165a
Revises: 170977060734
Create Date: 2022-02-04 19:37:47.074580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cde7b17165a'
down_revision = '170977060734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('imagefields_filename_key', 'imagefields', type_='unique')
    op.drop_constraint('imagefields_url_key', 'imagefields', type_='unique')
    op.drop_column('imagefields', 'filename')
    op.drop_column('imagefields', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagefields', sa.Column('url', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('imagefields', sa.Column('filename', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_unique_constraint('imagefields_url_key', 'imagefields', ['url'])
    op.create_unique_constraint('imagefields_filename_key', 'imagefields', ['filename'])
    # ### end Alembic commands ###
