"""added file and image field

Revision ID: 51d090de5b20
Revises: 4cde7b17165a
Create Date: 2022-02-04 19:38:04.586480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d090de5b20'
down_revision = '4cde7b17165a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('imagefields', sa.Column('filename', sa.String(length=100), nullable=False))
    op.add_column('imagefields', sa.Column('url', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'imagefields', ['url'])
    op.create_unique_constraint(None, 'imagefields', ['filename'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'imagefields', type_='unique')
    op.drop_constraint(None, 'imagefields', type_='unique')
    op.drop_column('imagefields', 'url')
    op.drop_column('imagefields', 'filename')
    # ### end Alembic commands ###
