"""added file and image field

Revision ID: 9f7a635bf8c0
Revises: 51d090de5b20
Create Date: 2022-02-04 19:38:33.245808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7a635bf8c0'
down_revision = '51d090de5b20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
