"""added file and image field

Revision ID: ce08fa37ff62
Revises: 9f7a635bf8c0
Create Date: 2022-02-04 19:41:45.728300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce08fa37ff62'
down_revision = '9f7a635bf8c0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
