"""added file and image field

Revision ID: ea9edc7e9cfa
Revises: 1c14c1bfca9f
Create Date: 2022-02-04 19:14:39.925036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea9edc7e9cfa'
down_revision = '1c14c1bfca9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
